export const RESOURCES = {
  EN: {
    NAV_DASHBOARD: 'MONITOR [F1]',
    NAV_MARKET: 'CHARTS [F2]',
    NAV_STRATEGY: 'DEV IDE [F3]',
    NAV_BACKTEST: 'BACKTEST [F4]',
    NAV_NEWS: 'NEWS [F5]',
    NAV_SCANNER: 'SCANNER [F6]',
    NAV_SETTINGS: 'SETUP',
    NAV_AI: 'AI ASSISTANT [F7]',
    PNL_WATCHLIST: 'WATCHLIST',
    PNL_CHART: 'PRIMARY CHART',
    PNL_TECH_CHART: 'TECHNICAL CHART',
    PNL_DEPTH: 'L2 DEPTH',
    PNL_SALES: 'TIME & SALES',
    PNL_PORTFOLIO: 'PORTFOLIO & RISK',
    PNL_ORDER: 'ORDER TICKET',
    PNL_IDE: 'QUANT STUDIO IDE',
    PNL_NEWS: 'REAL-TIME NEWS WIRE',
    PNL_SENTIMENT: 'SENTIMENT ANALYSIS',
    PNL_SCANNER: 'MARKET SCANNER',
    PNL_GEN_CONFIG: 'GENERAL CONFIG',
    PNL_PERF: 'STRATEGY PERFORMANCE REPORT',
    PNL_LOGS: 'EXECUTION LOGS',
    ORDER_LIMIT: 'LIMIT',
    ORDER_MARKET: 'MARKET',
    BTN_BUY: 'BUY / LONG',
    BTN_SELL: 'SELL / SHORT',
    TH_TICKER: 'TICKER',
    TH_LAST: 'LAST',
    TH_SYMBOL: 'SYMBOL',
    TH_QTY: 'QTY',
    TH_ENTRY: 'ENTRY',
    TH_MARK: 'MARK',
    TH_PNL: 'P&L',
    // Market view
    TAB_SECTORS: 'SECTORS',
    TAB_BOARDS: 'BOARDS',
    BOARD_CONCEPT: 'CONCEPT',
    BOARD_INDUSTRY: 'INDUSTRY',
    MARKET_OVERVIEW: 'MARKET OVERVIEW',
    INSTRUMENTS: 'INSTRUMENTS',
    UP: '↑ UP',
    DOWN: '↓ DN',
    FLAT: '→ FL',
    BREADTH: 'BREADTH',
    AVG_CHG: 'AVG CHG',
    TOTAL_VOL: 'TOTAL VOL',
    BTC_DOM: 'BTC DOM',
    TOP_GAINERS: 'TOP GAINERS',
    TOP_LOSERS: 'TOP LOSERS',
    MOST_ACTIVE: 'MOST ACTIVE',
    MARKET_INTEL_CRYPTO: 'MARKET INTELLIGENCE — CRYPTO / BINANCE USDT',
    MARKET_INTEL_ASHARE: 'MARKET INTELLIGENCE — A-SHARE MARKET',
    VIEWING_SNAPSHOT: 'VIEWING SNAPSHOT',
    CLICK_LIVE_RETURN: 'CLICK LIVE TO RETURN TO REAL-TIME',
    LOADING_BOARD_DATA: 'LOADING BOARD DATA…',
    BOARDS_CRYPTO_ONLY: 'BOARDS ONLY AVAILABLE FOR A-SHARE MARKET',
    NO_BOARD_DATA: 'NO BOARD DATA AVAILABLE',
    NEW_CONCEPT_SECTOR: 'NEW CONCEPT SECTOR',
    SECTOR_NAME: 'Sector Name',
    ENGLISH_NAME: 'English Name',
    SYMBOLS_LABEL: 'Symbols (comma or newline separated)',
    CRYPTO_SYMBOL_HINT: 'Use Binance pairs like BTC-USDT, ETH-USDT',
    STOCK_SYMBOL_HINT: 'Use A-share codes like sh600563, sz300510',
    BTN_CANCEL: 'CANCEL',
    BTN_CREATE: 'CREATE',
    BTN_REFRESH: 'REFRESH',
    BTN_CONCEPT: 'CONCEPT',
    // Board detail panel
    MAIN_INFLOW: 'Main',
    TURNOVER: 'Turnover',
    LEADER: 'Leader:',
    LOADING_STOCKS: 'LOADING STOCKS…',
    NO_COMPONENT_STOCKS: 'NO COMPONENT STOCKS',
    TH_CHG: 'CHG%',
    TH_VOL: 'VOL',
    // Sector detail panel
    NO_DATA_SYMBOL_MISMATCH: 'NO DATA — SYMBOLS MAY NOT MATCH MARKET MODE',
    NO_COMPONENTS: 'NO COMPONENTS IN UNIVERSE',
    FETCHING_DATA: 'FETCHING',
    DATA_SUFFIX: 'DATA…',
    INSUFFICIENT_HISTORY: 'INSUFFICIENT HISTORY FOR TREND VIEW',
    HISTORY_HINT_BOARD: 'Board data is sampled every 30s — check back shortly.',
    HISTORY_HINT_SECTOR: 'Data is sampled every 5 minutes — check back shortly.',
    LOADING_SECTOR_DATA: 'LOADING SECTOR DATA…',
    // Settings
    INTERFACE_LANGUAGE: 'INTERFACE LANGUAGE',
    DEFAULT_MARKET: 'DEFAULT MARKET',
    ASHARE_DATA_SOURCE: 'A-SHARE DATA SOURCE',
    ASHARE_ACTIVE_HINT: 'Active when market mode is A-SHARE',
    MULTI_ADAPTER_MODE: 'MULTI-ADAPTER MODE',
    MULTI_ADAPTER_HINT: 'Assign different data sources per capability',
    CAP_REALTIME: 'REALTIME QUOTES',
    CAP_DAILY: 'DAILY K-LINES',
    CAP_MINUTE: 'MINUTE K-LINES',
    COLOR_SCHEME: 'COLOR SCHEME',
    COLOR_SCHEME_HINT: 'Up/down color convention',
    COLOR_GREEN_RED: 'Green↑ Red↓',
    COLOR_RED_GREEN: 'Red↑ Green↓',
    RESET_FACTORY: 'RESET FACTORY SETTINGS',
    CONFIRM_RESET: 'CONFIRM RESET',
    RESET_MSG: 'Reset all settings and data to factory defaults? This action cannot be undone.',
    RESET_ALL: 'RESET ALL',
    CONFIGURATION: 'Configuration',
    SETUP_VERSION: 'Version',
    // Board timeline
    TIMELINE_1D: '1D',
    TIMELINE_3D: '3D',
    TIMELINE_1W: '1W',
    TIMELINE_ALL: 'ALL',
    // Common formatting
    FMT_YI: 'B',
    FMT_WAN: 'M',
    // AI assistant
    ERROR_PREFIX: '⚠ Error:',
    UNKNOWN_ERROR: 'Unknown error',
    AI_ASSISTANT: 'AI ASSISTANT',
    AI_POWERED_BY: 'powered by Claude',
    AI_BACKEND: 'BACKEND',
    AI_CLAUDE: 'CLAUDE',
    AI_CLEAR: 'Clear',
    AI_CLEAR_TITLE: 'Clear conversation',
    AI_BACKEND_NOT_RUNNING: 'Python backend not running. Run:',
    AI_CLAUDE_NOT_CONFIGURED: 'Claude API not configured. Set:',
    AI_MARKET_ASSISTANT: 'AI MARKET ASSISTANT',
    AI_DESCRIPTION: 'Chat with AI to search A-share stocks, create concept sectors, and manage your watchlist',
    AI_THINKING: 'Thinking…',
    AI_PROCESSING: 'Processing',
    AI_SEND: 'Send',
    AI_INPUT_PLACEHOLDER: 'Enter message… (Enter to send / Shift+Enter for newline)',
    AI_HINT: 'AI-created sectors are saved to the system · F2 to switch to market view',
    AI_SECTOR_CREATED: 'Sector created',
    AI_ADDED_TO_WATCHLIST: 'Added to watchlist',
    AI_STOCKS_SUFFIX: 'stocks',
    AI_ERROR: 'Error',
    AI_ERROR_HINT: 'Please confirm the Python backend is running (cd python && python main.py).',
    AI_TOOL_SEARCH: '🔍 Search stocks',
    AI_TOOL_SECTOR: '📊 Create sector',
    AI_TOOL_WATCHLIST: '⭐ Add to watchlist',
    AI_TOOL_GET_SECTORS: '📋 Query sectors',
    AI_SUGGESTION_1: 'Help me create an MLCC concept sector',
    AI_SUGGESTION_2: 'Search for RF chip companies in A-shares',
    AI_SUGGESTION_3: 'Create a domestic semiconductor replacement sector',
    AI_SUGGESTION_4: 'Find passive component A-share companies',
    AI_NOTIFICATION_SECTOR: 'AI created sector:',
    // Adapter names
    ADAPTER_EASTMONEY: 'EastMoney',
    ADAPTER_TENCENT: 'Tencent',
    ADAPTER_SINA: 'Sina',
    ADAPTER_BAOSTOCK: 'BaoStock',
    // Dashboard
    NO_WATCHLIST_DATA: 'NO WATCHLIST DATA',
    PRICE: 'PRICE',
    TIME: 'TIME',
    NAV_LABEL: 'NAV',
    DAY_PNL: 'DAY P&L',
    // Backtest
    RUN_STRATEGY_HINT: 'RUN STRATEGY FROM IDE TO GENERATE METRICS',
    EQUITY_CURVE: 'EQUITY CURVE',
    NO_BACKTEST_DATA: 'NO BACKTEST DATA',
    TRADE_LOG: 'TRADE LOG',
    SIDE: 'SIDE',
    // News
    NO_NEWS_LOADED: 'NO NEWS LOADED',
    REFRESH_FEED: 'REFRESH FEED',
    READER: 'READER',
    SELECT_ARTICLE: 'SELECT AN ARTICLE TO READ',
    // Scanner
    PRESETS: 'PRESETS',
    CONDITIONS: 'CONDITIONS',
    ADD: 'ADD',
    NO_CONDITIONS_SET: 'NO CONDITIONS SET',
    SELECT_PRESET_HINT: 'SELECT A PRESET OR ADD A CONDITION',
    SCANNER_IDLE: 'SCANNER IDLE',
    SET_CONDITIONS_HINT: 'Set conditions or choose a preset to run a live scan',
    NO_MATCHES: 'NO MATCHES',
    LOADING: 'LOADING…',
    LOADING_MARKET_DATA: 'Loading market data…',
    NO_INSTRUMENTS_PASS: 'No instruments pass all conditions',
    SCAN_RESULTS: 'SCAN RESULTS',
    NAME: 'NAME',
    CHG: 'CHG',
    VOLUME: 'VOLUME',
    SPREAD_PCT: 'SPREAD%',
    HITS: 'HITS',
    ADD_TO_WATCHLIST_TITLE: 'Add to watchlist',
    OPEN_CHART_TITLE: 'Open chart',
    // OrderBook
    AWAITING_DEPTH: 'Awaiting depth data…',
    SIZE: 'SIZE',
    SPREAD: 'SPREAD',
    // Order ticket
    ORDER_TYPE: 'ORDER TYPE',
    QUANTITY: 'QUANTITY',
    LIMIT_PRICE: 'LIMIT PRICE',
    // Command bar
    CMD_LABEL: 'CMD:',
    SRC_LABEL: 'SRC:',
    CMD_PLACEHOLDER: 'BUY BTC / ADD ETH…',
    LIVE: 'LIVE',
    PAPER: 'PAPER',
    HELP: 'HELP',
    MENU: 'MENU',
    CONNECTED: 'CNNCTD',
    CONNECTING: 'CNNCTNG',
    DISCONNECTED: 'DISCNCTD',
    LIVE_SWITCH_HINT: 'Click to switch to Paper mode',
    PAPER_SWITCH_HINT: 'Switch to Live trading (real funds)',
    // App
    NAVIGATE_VIEWS: 'NAVIGATE VIEWS',
    COMMANDS: 'COMMANDS',
    CMD_BUY_EXAMPLE: 'Market Buy 1 BTC',
    CMD_SELL_EXAMPLE: 'Market Sell 1 ETH',
    CMD_ADD_EXAMPLE: 'Add to Watchlist',
    CMD_REMOVE_EXAMPLE: 'Remove from Watchlist',
    RELOAD: 'RELOAD',
    ADD_SYMBOL: 'ADD SYMBOL',
    ADD_TO_WATCHLIST: 'ADD TO WATCHLIST',
    LIVE_ORDER_TITLE: '⚠ LIVE ORDER — REAL FUNDS',
    ACTION: 'ACTION',
    TOTAL: 'TOTAL',
    LIVE_ORDER_WARNING: 'This order will be executed against the live exchange and may result in real financial loss.',
    CONFIRM_SEND: 'CONFIRM & SEND',
    LIVE_TRADING: '🔴 LIVE TRADING',
    PAPER_TRADING: 'PAPER TRADING',
    // Panel
    MAXIMIZE: 'MAXIMIZE',
    RESTORE: 'RESTORE',
    CLOSE_PANEL: 'CLOSE PANEL',
    REFRESHING: 'REFRESHING…',
    // Titlebar
    TITLEBAR_TITLE: 'QuantCore Pro',
    // Titlebar menus
    MENU_FILE: 'File',
    MENU_VIEW: 'View',
    MENU_HELP: 'Help',
    MENU_RELOAD: 'Reload',
    MENU_FORCE_RELOAD: 'Force Reload',
    MENU_EXIT: 'Exit',
    MENU_TOGGLE_FULLSCREEN: 'Toggle Full Screen',
    MENU_ZOOM_IN: 'Zoom In',
    MENU_ZOOM_OUT: 'Zoom Out',
    MENU_RESET_ZOOM: 'Reset Zoom',
    MENU_TOGGLE_DEVTOOLS: 'Toggle Developer Tools',
    MENU_CHECK_UPDATES: 'Check for Updates…',
    MENU_DOCUMENTATION: 'Documentation',
    MENU_REPORT_ISSUE: 'Report Issue',
    MENU_ABOUT: 'About QuantCore Pro',
    // Update notifications
    UPDATE_CHECKING: 'Checking for updates…',
    UPDATE_AVAILABLE: 'A new version is available. Downloading…',
    UPDATE_NOT_AVAILABLE: 'You are using the latest version.',
    UPDATE_DOWNLOADING: 'Downloading update…',
    UPDATE_READY: 'Update downloaded — restart to install',
    UPDATE_RESTART: 'Restart to Update',
    UPDATE_ERROR: 'Update check failed',
  },
  CN: {
    NAV_DASHBOARD: '实盘监控 [F1]',
    NAV_MARKET: '市场图表 [F2]',
    NAV_STRATEGY: '策略开发 [F3]',
    NAV_BACKTEST: '历史回测 [F4]',
    NAV_NEWS: '新闻资讯 [F5]',
    NAV_SCANNER: '选股扫描 [F6]',
    NAV_SETTINGS: '系统设置',
    NAV_AI: 'AI 助手 [F7]',
    PNL_WATCHLIST: '自选列表',
    PNL_CHART: '主力合约图表',
    PNL_TECH_CHART: '技术分析图表',
    PNL_DEPTH: '深度图 (L2)',
    PNL_SALES: '成交明细',
    PNL_PORTFOLIO: '账户持仓 & 风控',
    PNL_ORDER: '下单面板',
    PNL_IDE: '量化策略工作室',
    PNL_NEWS: '实时新闻流',
    PNL_SENTIMENT: '情绪分析',
    PNL_SCANNER: '市场扫描器',
    PNL_GEN_CONFIG: '通用设置',
    PNL_PERF: '策略绩效报告',
    PNL_LOGS: '执行日志',
    ORDER_LIMIT: '限价单',
    ORDER_MARKET: '市价单',
    BTN_BUY: '买入 / 做多',
    BTN_SELL: '卖出 / 做空',
    TH_TICKER: '代码',
    TH_LAST: '最新价',
    TH_SYMBOL: '合约',
    TH_QTY: '数量',
    TH_ENTRY: '开仓均价',
    TH_MARK: '标记价格',
    TH_PNL: '盈亏',
    // Market view
    TAB_SECTORS: '板块',
    TAB_BOARDS: '题材',
    BOARD_CONCEPT: '概念板块',
    BOARD_INDUSTRY: '行业板块',
    MARKET_OVERVIEW: '市场概览',
    INSTRUMENTS: '标的数量',
    UP: '↑ 涨',
    DOWN: '↓ 跌',
    FLAT: '→ 平',
    BREADTH: '涨跌比',
    AVG_CHG: '平均涨跌',
    TOTAL_VOL: '总成交量',
    BTC_DOM: 'BTC 占比',
    TOP_GAINERS: '涨幅榜',
    TOP_LOSERS: '跌幅榜',
    MOST_ACTIVE: '活跃榜',
    MARKET_INTEL_CRYPTO: '市场情报 — 加密货币 / BINANCE USDT',
    MARKET_INTEL_ASHARE: '市场情报 — A股市场',
    VIEWING_SNAPSHOT: '查看快照',
    CLICK_LIVE_RETURN: '点击 LIVE 返回实时数据',
    LOADING_BOARD_DATA: '正在加载板块数据…',
    BOARDS_CRYPTO_ONLY: '板块功能仅适用于A股市场',
    NO_BOARD_DATA: '暂无板块数据',
    NEW_CONCEPT_SECTOR: '新建概念板块',
    SECTOR_NAME: '板块名称',
    ENGLISH_NAME: '英文名称',
    SYMBOLS_LABEL: '股票代码（逗号或换行分隔）',
    CRYPTO_SYMBOL_HINT: '使用 Binance 交易对，如 BTC-USDT, ETH-USDT',
    STOCK_SYMBOL_HINT: '使用A股代码，如 sh600563, sz300510',
    BTN_CANCEL: '取消',
    BTN_CREATE: '创建',
    BTN_REFRESH: '刷新',
    BTN_CONCEPT: '概念',
    // Board detail panel
    MAIN_INFLOW: '主力',
    TURNOVER: '换手',
    LEADER: '领涨:',
    LOADING_STOCKS: '正在加载股票…',
    NO_COMPONENT_STOCKS: '暂无成分股',
    TH_CHG: '涨跌幅',
    TH_VOL: '成交量',
    // Sector detail panel
    NO_DATA_SYMBOL_MISMATCH: '无数据 — 代码可能与市场模式不匹配',
    NO_COMPONENTS: '暂无成分股',
    FETCHING_DATA: '正在获取',
    DATA_SUFFIX: '数据…',
    INSUFFICIENT_HISTORY: '历史数据不足，无法显示趋势',
    HISTORY_HINT_BOARD: '板块数据每30秒采样一次，请稍候。',
    HISTORY_HINT_SECTOR: '数据每5分钟采样一次，请稍候。',
    LOADING_SECTOR_DATA: '正在加载板块数据…',
    // Settings
    INTERFACE_LANGUAGE: '界面语言',
    DEFAULT_MARKET: '默认市场',
    ASHARE_DATA_SOURCE: 'A股数据源',
    ASHARE_ACTIVE_HINT: '在A股模式下生效',
    MULTI_ADAPTER_MODE: '多数据源模式',
    MULTI_ADAPTER_HINT: '为不同功能分配不同数据源',
    CAP_REALTIME: '实时行情',
    CAP_DAILY: '日线数据',
    CAP_MINUTE: '分钟线数据',
    COLOR_SCHEME: '涨跌配色',
    COLOR_SCHEME_HINT: '涨跌颜色方案',
    COLOR_GREEN_RED: '绿涨红跌',
    COLOR_RED_GREEN: '红涨绿跌',
    RESET_FACTORY: '恢复出厂设置',
    CONFIRM_RESET: '确认重置',
    RESET_MSG: '将重置所有设置和数据为出厂默认值，此操作不可撤销。',
    RESET_ALL: '全部重置',
    CONFIGURATION: '系统配置',
    SETUP_VERSION: '版本',
    // Board timeline
    TIMELINE_1D: '1天',
    TIMELINE_3D: '3天',
    TIMELINE_1W: '1周',
    TIMELINE_ALL: '全部',
    // Common formatting
    FMT_YI: '亿',
    FMT_WAN: '万',
    // AI assistant
    ERROR_PREFIX: '⚠ 错误:',
    UNKNOWN_ERROR: '未知错误',
    AI_ASSISTANT: 'AI 助手',
    AI_POWERED_BY: '由 Claude 驱动',
    AI_BACKEND: '后端',
    AI_CLAUDE: 'CLAUDE',
    AI_CLEAR: '清空',
    AI_CLEAR_TITLE: '清空对话',
    AI_BACKEND_NOT_RUNNING: 'Python 后端未运行。请执行：',
    AI_CLAUDE_NOT_CONFIGURED: 'Claude API 未配置。请设置：',
    AI_MARKET_ASSISTANT: 'AI 市场助手',
    AI_DESCRIPTION: '通过自然语言对话，让 AI 帮你搜索 A 股股票、创建概念板块、管理自选股',
    AI_THINKING: '思考中…',
    AI_PROCESSING: '处理中',
    AI_SEND: '发送',
    AI_INPUT_PLACEHOLDER: '输入消息… (Enter 发送 / Shift+Enter 换行)',
    AI_HINT: 'AI 创建的板块会直接保存到系统 · F2 切换到行情页查看板块效果',
    AI_SECTOR_CREATED: '板块已创建',
    AI_ADDED_TO_WATCHLIST: '已加入自选股',
    AI_STOCKS_SUFFIX: '只股票',
    AI_ERROR: '错误',
    AI_ERROR_HINT: '请确认 Python 后端正在运行（cd python && python main.py）。',
    AI_TOOL_SEARCH: '🔍 搜索股票',
    AI_TOOL_SECTOR: '📊 创建板块',
    AI_TOOL_WATCHLIST: '⭐ 加入自选',
    AI_TOOL_GET_SECTORS: '📋 查询板块',
    AI_SUGGESTION_1: '帮我创建一个 MLCC 概念板块',
    AI_SUGGESTION_2: '搜索 A 股中射频芯片相关的公司',
    AI_SUGGESTION_3: '帮我创建国产替代半导体板块',
    AI_SUGGESTION_4: '查找做被动元件的 A 股公司',
    AI_NOTIFICATION_SECTOR: 'AI 已创建板块：',
    // Adapter names
    ADAPTER_EASTMONEY: '东方财富',
    ADAPTER_TENCENT: '腾讯财经',
    ADAPTER_SINA: '新浪财经',
    ADAPTER_BAOSTOCK: 'BaoStock',
    // Dashboard
    NO_WATCHLIST_DATA: '暂无自选数据',
    PRICE: '价格',
    TIME: '时间',
    NAV_LABEL: '净值',
    DAY_PNL: '当日盈亏',
    // Backtest
    RUN_STRATEGY_HINT: '从 IDE 运行策略以生成指标',
    EQUITY_CURVE: '权益曲线',
    NO_BACKTEST_DATA: '暂无回测数据',
    TRADE_LOG: '交易日志',
    SIDE: '方向',
    // News
    NO_NEWS_LOADED: '暂无新闻',
    REFRESH_FEED: '刷新新闻',
    READER: '阅读器',
    SELECT_ARTICLE: '选择一篇文章阅读',
    // Scanner
    PRESETS: '预设',
    CONDITIONS: '条件',
    ADD: '添加',
    NO_CONDITIONS_SET: '未设置条件',
    SELECT_PRESET_HINT: '选择预设或添加筛选条件',
    SCANNER_IDLE: '扫描器空闲',
    SET_CONDITIONS_HINT: '设置条件或选择预设开始实时扫描',
    NO_MATCHES: '无匹配',
    LOADING: '加载中…',
    LOADING_MARKET_DATA: '正在加载行情数据…',
    NO_INSTRUMENTS_PASS: '没有标的满足全部条件',
    SCAN_RESULTS: '扫描结果',
    NAME: '名称',
    CHG: '涨跌',
    VOLUME: '成交量',
    SPREAD_PCT: '价差%',
    HITS: '命中',
    ADD_TO_WATCHLIST_TITLE: '加入自选',
    OPEN_CHART_TITLE: '打开图表',
    // OrderBook
    AWAITING_DEPTH: '等待深度数据…',
    SIZE: '数量',
    SPREAD: '价差',
    // Order ticket
    ORDER_TYPE: '订单类型',
    QUANTITY: '数量',
    LIMIT_PRICE: '限价',
    // Command bar
    CMD_LABEL: '命令:',
    SRC_LABEL: '数据源:',
    CMD_PLACEHOLDER: 'BUY BTC / ADD ETH…',
    LIVE: '实盘',
    PAPER: '模拟',
    HELP: '帮助',
    MENU: '菜单',
    CONNECTED: '已连接',
    CONNECTING: '连接中',
    DISCONNECTED: '已断开',
    LIVE_SWITCH_HINT: '点击切换到模拟交易',
    PAPER_SWITCH_HINT: '切换到实盘交易（真实资金）',
    // App
    NAVIGATE_VIEWS: '切换视图',
    COMMANDS: '命令',
    CMD_BUY_EXAMPLE: '市价买入 1 BTC',
    CMD_SELL_EXAMPLE: '市价卖出 1 ETH',
    CMD_ADD_EXAMPLE: '加入自选',
    CMD_REMOVE_EXAMPLE: '移出自选',
    RELOAD: '重新加载',
    ADD_SYMBOL: '添加标的',
    ADD_TO_WATCHLIST: '加入自选',
    LIVE_ORDER_TITLE: '⚠ 实盘委托 — 真实资金',
    ACTION: '操作',
    TOTAL: '总计',
    LIVE_ORDER_WARNING: '此订单将在实盘交易所执行，可能导致真实的资金损失。',
    CONFIRM_SEND: '确认下单',
    LIVE_TRADING: '🔴 实盘交易',
    PAPER_TRADING: '模拟交易',
    // Panel
    MAXIMIZE: '最大化',
    RESTORE: '还原',
    CLOSE_PANEL: '关闭面板',
    REFRESHING: '刷新中…',
    // Titlebar
    TITLEBAR_TITLE: 'QuantCore Pro',
    // Titlebar menus
    MENU_FILE: '文件',
    MENU_VIEW: '视图',
    MENU_HELP: '帮助',
    MENU_RELOAD: '重新加载',
    MENU_FORCE_RELOAD: '强制重新加载',
    MENU_EXIT: '退出',
    MENU_TOGGLE_FULLSCREEN: '切换全屏',
    MENU_ZOOM_IN: '放大',
    MENU_ZOOM_OUT: '缩小',
    MENU_RESET_ZOOM: '重置缩放',
    MENU_TOGGLE_DEVTOOLS: '切换开发者工具',
    MENU_CHECK_UPDATES: '检查更新…',
    MENU_DOCUMENTATION: '文档',
    MENU_REPORT_ISSUE: '报告问题',
    MENU_ABOUT: '关于 QuantCore Pro',
    // Update notifications
    UPDATE_CHECKING: '正在检查更新…',
    UPDATE_AVAILABLE: '发现新版本，正在下载…',
    UPDATE_NOT_AVAILABLE: '当前已是最新版本。',
    UPDATE_DOWNLOADING: '正在下载更新…',
    UPDATE_READY: '更新已下载 — 重启以安装',
    UPDATE_RESTART: '重启以更新',
    UPDATE_ERROR: '检查更新失败',
  },
} as const;

export type ResourceKey = keyof typeof RESOURCES['EN'];
export type LangKey = keyof typeof RESOURCES;
