export const RESOURCES = {
  EN: {
    NAV_DASHBOARD: 'MONITOR [F1]',
    NAV_MARKET: 'CHARTS [F2]',
    NAV_STRATEGY: 'DEV IDE [F3]',
    NAV_BACKTEST: 'BACKTEST [F4]',
    NAV_NEWS: 'NEWS [F5]',
    NAV_SCANNER: 'SCANNER [F6]',
    NAV_SETTINGS: 'SETUP',
    PNL_WATCHLIST: 'WATCHLIST',
    PNL_CHART: 'PRIMARY CHART',
    PNL_TECH_CHART: 'TECHNICAL CHART',
    PNL_DEPTH: 'L2 DEPTH',
    PNL_SALES: 'TIME & SALES',
    PNL_PORTFOLIO: 'PORTFOLIO & RISK',
    PNL_ORDER: 'ORDER TICKET',
    PNL_IDE: 'QUANT STUDIO IDE',
    PNL_NEWS: 'REAL-TIME NEWS WIRE',
    PNL_SENTIMENT: 'SENTIMENT ANALYSIS',
    PNL_SCANNER: 'MARKET SCANNER',
    PNL_GEN_CONFIG: 'GENERAL CONFIG',
    PNL_PERF: 'STRATEGY PERFORMANCE REPORT',
    PNL_LOGS: 'EXECUTION LOGS',
    ORDER_LIMIT: 'LIMIT',
    ORDER_MARKET: 'MARKET',
    BTN_BUY: 'BUY / LONG',
    BTN_SELL: 'SELL / SHORT',
    TH_TICKER: 'TICKER',
    TH_LAST: 'LAST',
    TH_SYMBOL: 'SYMBOL',
    TH_QTY: 'QTY',
    TH_ENTRY: 'ENTRY',
    TH_MARK: 'MARK',
    TH_PNL: 'P&L',
    // Market view
    TAB_SECTORS: 'SECTORS',
    TAB_BOARDS: 'BOARDS',
    BOARD_CONCEPT: 'CONCEPT',
    BOARD_INDUSTRY: 'INDUSTRY',
    MARKET_OVERVIEW: 'MARKET OVERVIEW',
    INSTRUMENTS: 'INSTRUMENTS',
    UP: '↑ UP',
    DOWN: '↓ DN',
    FLAT: '→ FL',
    BREADTH: 'BREADTH',
    AVG_CHG: 'AVG CHG',
    TOTAL_VOL: 'TOTAL VOL',
    BTC_DOM: 'BTC DOM',
    TOP_GAINERS: 'TOP GAINERS',
    TOP_LOSERS: 'TOP LOSERS',
    MOST_ACTIVE: 'MOST ACTIVE',
    MARKET_INTEL_CRYPTO: 'MARKET INTELLIGENCE — CRYPTO / BINANCE USDT',
    MARKET_INTEL_ASHARE: 'MARKET INTELLIGENCE — A-SHARE MARKET',
    VIEWING_SNAPSHOT: 'VIEWING SNAPSHOT',
    CLICK_LIVE_RETURN: 'CLICK LIVE TO RETURN TO REAL-TIME',
    LOADING_BOARD_DATA: 'LOADING BOARD DATA…',
    BOARDS_CRYPTO_ONLY: 'BOARDS ONLY AVAILABLE FOR A-SHARE MARKET',
    NO_BOARD_DATA: 'NO BOARD DATA AVAILABLE',
    NEW_CONCEPT_SECTOR: 'NEW CONCEPT SECTOR',
    SECTOR_NAME: 'Sector Name',
    ENGLISH_NAME: 'English Name',
    SYMBOLS_LABEL: 'Symbols (comma or newline separated)',
    CRYPTO_SYMBOL_HINT: 'Use Binance pairs like BTC-USDT, ETH-USDT',
    STOCK_SYMBOL_HINT: 'Use A-share codes like sh600563, sz300510',
    BTN_CANCEL: 'CANCEL',
    BTN_CREATE: 'CREATE',
    BTN_REFRESH: 'REFRESH',
    BTN_CONCEPT: 'CONCEPT',
    // Board detail panel
    MAIN_INFLOW: 'Main',
    TURNOVER: 'Turnover',
    LEADER: 'Leader:',
    LOADING_STOCKS: 'LOADING STOCKS…',
    NO_COMPONENT_STOCKS: 'NO COMPONENT STOCKS',
    TH_CHG: 'CHG%',
    TH_VOL: 'VOL',
    // Sector detail panel
    NO_DATA_SYMBOL_MISMATCH: 'NO DATA — SYMBOLS MAY NOT MATCH MARKET MODE',
    NO_COMPONENTS: 'NO COMPONENTS IN UNIVERSE',
    FETCHING_DATA: 'FETCHING',
    DATA_SUFFIX: 'DATA…',
    INSUFFICIENT_HISTORY: 'INSUFFICIENT HISTORY FOR TREND VIEW',
    HISTORY_HINT_BOARD: 'Board data is sampled every 30s — check back shortly.',
    HISTORY_HINT_SECTOR: 'Data is sampled every 5 minutes — check back shortly.',
    LOADING_SECTOR_DATA: 'LOADING SECTOR DATA…',
    // Settings
    INTERFACE_LANGUAGE: 'INTERFACE LANGUAGE',
    DEFAULT_MARKET: 'DEFAULT MARKET',
    ASHARE_DATA_SOURCE: 'A-SHARE DATA SOURCE',
    ASHARE_ACTIVE_HINT: 'Active when market mode is A-SHARE',
    MULTI_ADAPTER_MODE: 'MULTI-ADAPTER MODE',
    MULTI_ADAPTER_HINT: 'Assign different data sources per capability',
    CAP_REALTIME: 'REALTIME QUOTES',
    CAP_DAILY: 'DAILY K-LINES',
    CAP_MINUTE: 'MINUTE K-LINES',
    COLOR_SCHEME: 'COLOR SCHEME',
    COLOR_SCHEME_HINT: 'Up/down color convention',
    COLOR_GREEN_RED: 'Green↑ Red↓',
    COLOR_RED_GREEN: 'Red↑ Green↓',
    RESET_FACTORY: 'RESET FACTORY SETTINGS',
    CONFIRM_RESET: 'CONFIRM RESET',
    RESET_MSG: 'Reset all settings and data to factory defaults? This action cannot be undone.',
    RESET_ALL: 'RESET ALL',
    CONFIGURATION: 'Configuration',
    // Board timeline
    TIMELINE_1D: '1D',
    TIMELINE_3D: '3D',
    TIMELINE_1W: '1W',
    TIMELINE_ALL: 'ALL',
    // Common formatting
    FMT_YI: 'B',
    FMT_WAN: 'M',
    // AI assistant
    ERROR_PREFIX: '⚠ Error:',
    UNKNOWN_ERROR: 'Unknown error',
    // Adapter names
    ADAPTER_EASTMONEY: 'EastMoney',
    ADAPTER_TENCENT: 'Tencent',
    ADAPTER_SINA: 'Sina',
    ADAPTER_BAOSTOCK: 'BaoStock',
  },
  CN: {
    NAV_DASHBOARD: '实盘监控 [F1]',
    NAV_MARKET: '市场图表 [F2]',
    NAV_STRATEGY: '策略开发 [F3]',
    NAV_BACKTEST: '历史回测 [F4]',
    NAV_NEWS: '新闻资讯 [F5]',
    NAV_SCANNER: '选股扫描 [F6]',
    NAV_SETTINGS: '系统设置',
    PNL_WATCHLIST: '自选列表',
    PNL_CHART: '主力合约图表',
    PNL_TECH_CHART: '技术分析图表',
    PNL_DEPTH: '深度图 (L2)',
    PNL_SALES: '成交明细',
    PNL_PORTFOLIO: '账户持仓 & 风控',
    PNL_ORDER: '下单面板',
    PNL_IDE: '量化策略工作室',
    PNL_NEWS: '实时新闻流',
    PNL_SENTIMENT: '情绪分析',
    PNL_SCANNER: '市场扫描器',
    PNL_GEN_CONFIG: '通用设置',
    PNL_PERF: '策略绩效报告',
    PNL_LOGS: '执行日志',
    ORDER_LIMIT: '限价单',
    ORDER_MARKET: '市价单',
    BTN_BUY: '买入 / 做多',
    BTN_SELL: '卖出 / 做空',
    TH_TICKER: '代码',
    TH_LAST: '最新价',
    TH_SYMBOL: '合约',
    TH_QTY: '数量',
    TH_ENTRY: '开仓均价',
    TH_MARK: '标记价格',
    TH_PNL: '盈亏',
    // Market view
    TAB_SECTORS: '板块',
    TAB_BOARDS: '题材',
    BOARD_CONCEPT: '概念板块',
    BOARD_INDUSTRY: '行业板块',
    MARKET_OVERVIEW: '市场概览',
    INSTRUMENTS: '标的数量',
    UP: '↑ 涨',
    DOWN: '↓ 跌',
    FLAT: '→ 平',
    BREADTH: '涨跌比',
    AVG_CHG: '平均涨跌',
    TOTAL_VOL: '总成交量',
    BTC_DOM: 'BTC 占比',
    TOP_GAINERS: '涨幅榜',
    TOP_LOSERS: '跌幅榜',
    MOST_ACTIVE: '活跃榜',
    MARKET_INTEL_CRYPTO: '市场情报 — 加密货币 / BINANCE USDT',
    MARKET_INTEL_ASHARE: '市场情报 — A股市场',
    VIEWING_SNAPSHOT: '查看快照',
    CLICK_LIVE_RETURN: '点击 LIVE 返回实时数据',
    LOADING_BOARD_DATA: '正在加载板块数据…',
    BOARDS_CRYPTO_ONLY: '板块功能仅适用于A股市场',
    NO_BOARD_DATA: '暂无板块数据',
    NEW_CONCEPT_SECTOR: '新建概念板块',
    SECTOR_NAME: '板块名称',
    ENGLISH_NAME: '英文名称',
    SYMBOLS_LABEL: '股票代码（逗号或换行分隔）',
    CRYPTO_SYMBOL_HINT: '使用 Binance 交易对，如 BTC-USDT, ETH-USDT',
    STOCK_SYMBOL_HINT: '使用A股代码，如 sh600563, sz300510',
    BTN_CANCEL: '取消',
    BTN_CREATE: '创建',
    BTN_REFRESH: '刷新',
    BTN_CONCEPT: '概念',
    // Board detail panel
    MAIN_INFLOW: '主力',
    TURNOVER: '换手',
    LEADER: '领涨:',
    LOADING_STOCKS: '正在加载股票…',
    NO_COMPONENT_STOCKS: '暂无成分股',
    TH_CHG: '涨跌幅',
    TH_VOL: '成交量',
    // Sector detail panel
    NO_DATA_SYMBOL_MISMATCH: '无数据 — 代码可能与市场模式不匹配',
    NO_COMPONENTS: '暂无成分股',
    FETCHING_DATA: '正在获取',
    DATA_SUFFIX: '数据…',
    INSUFFICIENT_HISTORY: '历史数据不足，无法显示趋势',
    HISTORY_HINT_BOARD: '板块数据每30秒采样一次，请稍候。',
    HISTORY_HINT_SECTOR: '数据每5分钟采样一次，请稍候。',
    LOADING_SECTOR_DATA: '正在加载板块数据…',
    // Settings
    INTERFACE_LANGUAGE: '界面语言',
    DEFAULT_MARKET: '默认市场',
    ASHARE_DATA_SOURCE: 'A股数据源',
    ASHARE_ACTIVE_HINT: '在A股模式下生效',
    MULTI_ADAPTER_MODE: '多数据源模式',
    MULTI_ADAPTER_HINT: '为不同功能分配不同数据源',
    CAP_REALTIME: '实时行情',
    CAP_DAILY: '日线数据',
    CAP_MINUTE: '分钟线数据',
    COLOR_SCHEME: '涨跌配色',
    COLOR_SCHEME_HINT: '涨跌颜色方案',
    COLOR_GREEN_RED: '绿涨红跌',
    COLOR_RED_GREEN: '红涨绿跌',
    RESET_FACTORY: '恢复出厂设置',
    CONFIRM_RESET: '确认重置',
    RESET_MSG: '将重置所有设置和数据为出厂默认值，此操作不可撤销。',
    RESET_ALL: '全部重置',
    CONFIGURATION: '系统配置',
    // Board timeline
    TIMELINE_1D: '1天',
    TIMELINE_3D: '3天',
    TIMELINE_1W: '1周',
    TIMELINE_ALL: '全部',
    // Common formatting
    FMT_YI: '亿',
    FMT_WAN: '万',
    // AI assistant
    ERROR_PREFIX: '⚠ 错误:',
    UNKNOWN_ERROR: '未知错误',
    // Adapter names
    ADAPTER_EASTMONEY: '东方财富',
    ADAPTER_TENCENT: '腾讯财经',
    ADAPTER_SINA: '新浪财经',
    ADAPTER_BAOSTOCK: 'BaoStock',
  },
} as const;

export type ResourceKey = keyof typeof RESOURCES['EN'];
export type LangKey = keyof typeof RESOURCES;
