export const RESOURCES = {
  EN: {
    NAV_DASHBOARD: 'MONITOR [F1]',
    NAV_MARKET: 'CHARTS [F2]',
    NAV_STRATEGY: 'DEV IDE [F3]',
    NAV_BACKTEST: 'BACKTEST [F4]',
    NAV_NEWS: 'NEWS [F5]',
    NAV_SCANNER: 'SCANNER [F6]',
    NAV_SETTINGS: 'SETUP',
    PNL_WATCHLIST: 'WATCHLIST',
    PNL_CHART: 'PRIMARY CHART',
    PNL_TECH_CHART: 'TECHNICAL CHART',
    PNL_DEPTH: 'L2 DEPTH',
    PNL_SALES: 'TIME & SALES',
    PNL_PORTFOLIO: 'PORTFOLIO & RISK',
    PNL_ORDER: 'ORDER TICKET',
    PNL_IDE: 'QUANT STUDIO IDE',
    PNL_NEWS: 'REAL-TIME NEWS WIRE',
    PNL_SENTIMENT: 'SENTIMENT ANALYSIS',
    PNL_SCANNER: 'MARKET SCANNER',
    PNL_GEN_CONFIG: 'GENERAL CONFIG',
    PNL_PERF: 'STRATEGY PERFORMANCE REPORT',
    PNL_LOGS: 'EXECUTION LOGS',
    ORDER_LIMIT: 'LIMIT',
    ORDER_MARKET: 'MARKET',
    BTN_BUY: 'BUY / LONG',
    BTN_SELL: 'SELL / SHORT',
    TH_TICKER: 'TICKER',
    TH_LAST: 'LAST',
    TH_SYMBOL: 'SYMBOL',
    TH_QTY: 'QTY',
    TH_ENTRY: 'ENTRY',
    TH_MARK: 'MARK',
    TH_PNL: 'P&L',
  },
  CN: {
    NAV_DASHBOARD: '实盘监控 [F1]',
    NAV_MARKET: '市场图表 [F2]',
    NAV_STRATEGY: '策略开发 [F3]',
    NAV_BACKTEST: '历史回测 [F4]',
    NAV_NEWS: '新闻资讯 [F5]',
    NAV_SCANNER: '选股扫描 [F6]',
    NAV_SETTINGS: '系统设置',
    PNL_WATCHLIST: '自选列表',
    PNL_CHART: '主力合约图表',
    PNL_TECH_CHART: '技术分析图表',
    PNL_DEPTH: '深度图 (L2)',
    PNL_SALES: '成交明细',
    PNL_PORTFOLIO: '账户持仓 & 风控',
    PNL_ORDER: '下单面板',
    PNL_IDE: '量化策略工作室',
    PNL_NEWS: '实时新闻流',
    PNL_SENTIMENT: '情绪分析',
    PNL_SCANNER: '市场扫描器',
    PNL_GEN_CONFIG: '通用设置',
    PNL_PERF: '策略绩效报告',
    PNL_LOGS: '执行日志',
    ORDER_LIMIT: '限价单',
    ORDER_MARKET: '市价单',
    BTN_BUY: '买入 / 做多',
    BTN_SELL: '卖出 / 做空',
    TH_TICKER: '代码',
    TH_LAST: '最新价',
    TH_SYMBOL: '合约',
    TH_QTY: '数量',
    TH_ENTRY: '开仓均价',
    TH_MARK: '标记价格',
    TH_PNL: '盈亏',
  },
} as const;

export type ResourceKey = keyof typeof RESOURCES['EN'];
export type LangKey = keyof typeof RESOURCES;
